# fly.toml app configuration file generated for music-genre-api on 2025-08-19T21:01:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'music-genre-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'performance-1x'
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
